"""Renders a DocumentSpec to a styled A4 PDF with ReportLab."""

from datetime import UTC, datetime
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

from app.documents.specs import DocumentSpec

INK = colors.HexColor("#1E293B")
MUTED = colors.HexColor("#64748B")
ACCENT = colors.HexColor("#4F46E5")


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=base["Title"], fontSize=28, leading=34, textColor=INK, alignment=TA_CENTER),
        "subtitle": ParagraphStyle("st", parent=base["Normal"], fontSize=13, textColor=MUTED, alignment=TA_CENTER),
        "meta": ParagraphStyle("m", parent=base["Normal"], fontSize=9, textColor=MUTED, alignment=TA_CENTER),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"], fontSize=16, textColor=ACCENT, spaceBefore=14, spaceAfter=6
        ),
        "body": ParagraphStyle("b", parent=base["BodyText"], fontSize=11, leading=16, textColor=INK, spaceAfter=8),
    }


def _p(text: str, style: ParagraphStyle) -> Paragraph:
    # Paragraph parses a mini-markup language; escape model output so a stray
    # "<" cannot break rendering.
    return Paragraph(escape(text), style)


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(20 * mm, 12 * mm, "Generated by CortexAI")
    canvas.drawRightString(A4[0] - 20 * mm, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_pdf(spec: DocumentSpec) -> bytes:
    s = _styles()
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=22 * mm,
        bottomMargin=22 * mm,
        title=spec.title,
        author="CortexAI",
    )

    story: list = [Spacer(1, 60 * mm), _p(spec.title, s["title"])]
    if spec.subtitle:
        story += [Spacer(1, 4 * mm), _p(spec.subtitle, s["subtitle"])]
    story += [
        Spacer(1, 10 * mm),
        _p(datetime.now(UTC).strftime("%d %B %Y"), s["meta"]),
        PageBreak(),
        _p("Introduction", s["h2"]),
        _p(spec.introduction, s["body"]),
    ]
    for section in spec.sections:
        story.append(_p(section.heading, s["h2"]))
        story += [_p(par, s["body"]) for par in section.paragraphs]
        if section.bullets:
            story.append(
                ListFlowable(
                    [ListItem(_p(b, s["body"]), leftIndent=12) for b in section.bullets],
                    bulletType="bullet",
                    bulletColor=ACCENT,
                    leftIndent=14,
                )
            )
    story += [
        Spacer(1, 4 * mm),
        HRFlowable(width="100%", color=colors.HexColor("#E2E8F0")),
        _p("Conclusion", s["h2"]),
        _p(spec.conclusion, s["body"]),
    ]
    doc.build(story, onLaterPages=_footer)
    return buf.getvalue()
