"""Renders a DeckSpec to a 16:9 PowerPoint deck with python-pptx.

The visual design (dark cover, card-style bullets, metric tiles, accent
conclusion slide) mirrors the original CortexAI templates.
"""

from io import BytesIO

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Emu, Inches, Pt

from app.documents.specs import DeckSpec, Slide

DARK = RGBColor(0x0F, 0x17, 0x2A)
PRIMARY = RGBColor(0x25, 0x63, 0xEB)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
TEXT = RGBColor(0x1E, 0x29, 0x3B)
MUTED = RGBColor(0x64, 0x74, 0x8B)
CARD = RGBColor(0xEF, 0xF6, 0xFF)
CARD_ALT = RGBColor(0xF8, 0xFA, 0xFC)
TILE = RGBColor(0x1E, 0x3A, 0x5F)
SOFT = RGBColor(0xBF, 0xDB, 0xFE)

W, H = Inches(13.333), Inches(7.5)


def _bg(slide, color: RGBColor) -> None:
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _shape(slide, kind, x, y, w, h, color: RGBColor, line: RGBColor | None = None):
    shp = slide.shapes.add_shape(kind, x, y, w, h)
    shp.fill.solid()
    shp.fill.fore_color.rgb = color
    if line is None:
        shp.line.fill.background()
    else:
        shp.line.color.rgb = line
    shp.shadow.inherit = False
    return shp


def _text(
    slide,
    text: str,
    x,
    y,
    w,
    h,
    size: int,
    color: RGBColor,
    bold: bool = False,
    align=PP_ALIGN.LEFT,
    anchor=MSO_ANCHOR.TOP,
) -> None:
    box = slide.shapes.add_textbox(x, y, w, h)
    tf = box.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    run.font.name = "Calibri"


def _cover(prs, title: str, subtitle: str) -> None:
    s = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(s, DARK)
    _shape(s, MSO_SHAPE.OVAL, Inches(10.3), Inches(-1.2), Inches(4), Inches(4), TILE)
    _shape(s, MSO_SHAPE.OVAL, Inches(-0.8), Inches(5.5), Inches(2.5), Inches(2.5), TILE)
    _text(s, title, Inches(0.8), Inches(2.4), Inches(11.7), Inches(1.4), 40, WHITE, True, PP_ALIGN.CENTER)
    if subtitle:
        _text(s, subtitle, Inches(0.8), Inches(3.9), Inches(11.7), Inches(0.8), 18, SOFT, align=PP_ALIGN.CENTER)
    _text(
        s,
        "Generated by CortexAI",
        Inches(0.8),
        Inches(6.8),
        Inches(11.7),
        Inches(0.4),
        10,
        MUTED,
        align=PP_ALIGN.CENTER,
    )


def _header(s, idx: int, title: str, dark: bool) -> None:
    _text(s, title, Inches(0.6), Inches(0.3), Inches(11.4), Inches(0.8), 28, WHITE if dark else PRIMARY, True)
    bar = _shape(s, MSO_SHAPE.RECTANGLE, Inches(0.6), Inches(1.1), Inches(12.1), Emu(20000), PRIMARY)
    bar.line.fill.background()
    badge = _shape(s, MSO_SHAPE.OVAL, Inches(12.3), Inches(0.35), Inches(0.5), Inches(0.5), PRIMARY)
    badge.text_frame.text = str(idx)
    para = badge.text_frame.paragraphs[0]
    para.alignment = PP_ALIGN.CENTER
    para.runs[0].font.size = Pt(11)
    para.runs[0].font.bold = True
    para.runs[0].font.color.rgb = WHITE


def _bullets(prs, idx: int, sl: Slide) -> None:
    s = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(s, WHITE)
    _header(s, idx, sl.title, dark=False)
    items = sl.bullets[:6] or [""]
    card_h, gap, top = Inches(0.78), Inches(0.14), Inches(1.4)
    for i, item in enumerate(items):
        y = top + i * (card_h + gap)
        _shape(
            s,
            MSO_SHAPE.ROUNDED_RECTANGLE,
            Inches(0.6),
            y,
            Inches(12.1),
            card_h,
            CARD if i % 2 == 0 else CARD_ALT,
            RGBColor(0xDB, 0xEA, 0xFE),
        )
        _shape(s, MSO_SHAPE.OVAL, Inches(0.85), y + Inches(0.28), Inches(0.22), Inches(0.22), PRIMARY)
        _text(s, item, Inches(1.25), y, Inches(11.2), card_h, 16, TEXT, anchor=MSO_ANCHOR.MIDDLE)


def _stats(prs, idx: int, sl: Slide) -> None:
    s = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(s, DARK)
    _header(s, idx, sl.title, dark=True)
    stats = sl.stats[:4]
    if not stats:  # model chose "stats" but gave no numbers; degrade to bullets
        return _bullets_on(s, sl)
    col_w = Inches(12.1) / len(stats)
    for i, st in enumerate(stats):
        x = Inches(0.6) + int(col_w * i)
        _shape(
            s,
            MSO_SHAPE.ROUNDED_RECTANGLE,
            x + Inches(0.1),
            Inches(1.7),
            int(col_w) - Inches(0.2),
            Inches(4.2),
            TILE,
            PRIMARY,
        )
        _text(
            s,
            st.value,
            x + Inches(0.1),
            Inches(2.3),
            int(col_w) - Inches(0.2),
            Inches(1.4),
            40,
            RGBColor(0x60, 0xA5, 0xFA),
            True,
            PP_ALIGN.CENTER,
        )
        _text(
            s,
            st.label,
            x + Inches(0.2),
            Inches(3.9),
            int(col_w) - Inches(0.4),
            Inches(1.6),
            16,
            RGBColor(0xCB, 0xD5, 0xE1),
            align=PP_ALIGN.CENTER,
        )
    return None


def _bullets_on(s, sl: Slide) -> None:
    for i, item in enumerate(sl.bullets[:6]):
        _text(s, f"•  {item}", Inches(0.8), Inches(1.6) + i * Inches(0.8), Inches(11.5), Inches(0.7), 18, WHITE)


def _conclusion(prs, sl: Slide) -> None:
    s = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(s, PRIMARY)
    _shape(s, MSO_SHAPE.OVAL, Inches(9.8), Inches(4.2), Inches(5), Inches(5), RGBColor(0x1D, 0x4E, 0xD8))
    _text(s, sl.title, Inches(0.8), Inches(1.0), Inches(9), Inches(1.0), 36, WHITE, True)
    _text(s, "Key takeaways", Inches(0.8), Inches(2.1), Inches(9), Inches(0.5), 16, SOFT)
    for i, point in enumerate(sl.bullets[:5]):
        y = Inches(2.8) + i * Inches(0.8)
        _shape(s, MSO_SHAPE.OVAL, Inches(0.85), y + Inches(0.15), Inches(0.28), Inches(0.28), WHITE)
        _text(s, point, Inches(1.35), y, Inches(8.8), Inches(0.7), 18, WHITE)


def build_pptx(spec: DeckSpec) -> bytes:
    prs = Presentation()
    prs.slide_width, prs.slide_height = W, H
    prs.core_properties.title = spec.title
    prs.core_properties.author = "CortexAI"

    _cover(prs, spec.title, spec.subtitle)
    for idx, sl in enumerate(spec.slides, start=1):
        if sl.type == "stats":
            _stats(prs, idx, sl)
        elif sl.type == "conclusion":
            _conclusion(prs, sl)
        else:
            _bullets(prs, idx, sl)

    buf = BytesIO()
    prs.save(buf)
    return buf.getvalue()
